#!/bin/bash

ME=$(basename "$0")

function usage {
   echo "Usage: $ME station|base|clean" >&2
   exit 1
}

if [[ $(dirname "$0") != . ]]; then
    echo "Error: $ME must be called within the project root directory!" >&2
fi

case "$1" in
    station|s*)
        ln -sf Makefile_station Makefile
        ln -sf config_station.h config.h
        rm -f *.o *.elf *.lss *.lst *.map *.eep *.hex *.sym
        rm -rf .dep
        ctags -Re -f TAGS *.[ch]
        ;;
    base|b*)
        ln -sf Makefile_base Makefile
        ln -sf config_base.h config.h
        rm -f *.o *.elf *.lss *.lst *.map *.eep *.hex *.sym
        rm -rf .dep
        ctags -Re -f TAGS *.[ch]
        ;;
    clean|c*)
        if [ -f Makefile ]; then
            make clean
        fi
        rm -f Makefile config.h TAGS
        ;;
    *)
        usage
        ;;
esac

# EOF
